---
# bootstrap из kafka01 для web01.
kafka_bootstrap_servers: >-
  {{ hostvars['kafka01'].ansible_host }}:9092,{{ hostvars['kafka01'].ansible_host }}:9094,{{ hostvars['kafka01'].ansible_host }}:9096
