---
# roles/kafka/tasks/main.yml

- name: Обновить список пакетов
  apt:
    update_cache: yes

- name: Установить Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Debug kafka_version
  debug:
    var: kafka_version

- name: Debug kafka_ui_external_port
  debug:
    var: kafka_scala_version

- name: Скачать Kafka
  get_url:
    url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka.tgz"

- name: Распаковать Kafka
  unarchive:
    src: "/tmp/kafka.tgz"
    dest: "/opt/"
    remote_src: yes

- name: Переименовать директорию Kafka
  ansible.builtin.command:
    cmd: "mv /opt/kafka_{{ kafka_scala_version }}-{{ kafka_version }} /opt/kafka"
    creates: "/opt/kafka"

- name: Настроить Kafka (server.properties)
  lineinfile:
    path: "/opt/kafka/config/server.properties"
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - { key: "broker.id", value: "1" }
    - { key: "log.dirs", value: "/tmp/kafka-logs" }
    - { key: "zookeeper.connect", value: "localhost:2181" }
    - { key: "listeners", value: "PLAINTEXT://:9092" }

- name: Запустить ZooKeeper
  ansible.builtin.shell: "/opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties &"
  args:
    executable: /bin/bash

- name: Запустить Kafka
  ansible.builtin.shell: "/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties &"
  args:
    executable: /bin/bash

- name: Создаём топик
  ansible.builtin.shell: "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic test-topic --partitions 1 --replication-factor 1"
  args:
    executable: /bin/bash