- name: Обновить список пакетов
  ansible.builtin.apt:
    update_cache: yes

- name: Установить Java
  ansible.builtin.apt:
    name: openjdk-11-jdk
    state: present

- name: Скачать Kafka
  ansible.builtin.get_url:
    url: "https://dlcdn.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka.tgz"

- name: Распаковать Kafka
  ansible.builtin.unarchive:
    src: "/tmp/kafka.tgz"
    dest: "/opt/"
    remote_src: yes

- name: Переименовать директорию Kafka
  ansible.builtin.command:
    cmd: "mv /opt/kafka_{{ kafka_scala_version }}-{{ kafka_version }} /opt/kafka"
    creates: "/opt/kafka"

- name: Настроить Kafka (server.properties)
  ansible.builtin.lineinfile:
    path: "/opt/kafka/config/server.properties"
    regexp: "^{{ item.key }}=.*"
    line: "{{ item.key }}={{ item.value }}"
  loop: "{{ kafka_server_properties }}"

- name: Запустить ZooKeeper
  ansible.builtin.shell: "/opt/kafka/bin/zookeeper-server-start.sh /opt/kafka/config/zookeeper.properties &"
  args:
    executable: /bin/bash

- name: Запустить Kafka
  ansible.builtin.shell: "/opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties &"
  args:
    executable: /bin/bash

- name: Проверить существование топика
  ansible.builtin.command: "/opt/kafka/bin/kafka-topics.sh --bootstrap-server {{ kafka_bootstrap_server }} --list"
  register: kafka_topics

- name: Создать топик, если он не существует
  ansible.builtin.shell: "/opt/kafka/bin/kafka-topics.sh --bootstrap-server {{ kafka_bootstrap_server }} --create --topic {{ kafka_topic_name }} --partitions {{ kafka_topic_partitions }} --replication-factor {{ kafka_topic_replication_factor }}"
  args:
    executable: /bin/bash
  when: kafka_topic_name not in kafka_topics.stdout_lines