stages:
  - build
  - push
  - deploy
  - cleanup

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  NEXUS_IMAGE_NAME: 89.169.189.228:5000/$CI_PROJECT_NAME:$CI_COMMIT_SHA # HTTP Nexus
  # NEXUS_IMAGE_NAME: <yourdomain.com>:8443/$CI_PROJECT_NAME:$CI_COMMIT_SHA # HTTPS Nexus

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  tags:
    - docker
    - app01

push_to_nexus:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u admin -p Tanaktank12 89.169.189.228:5000  # HTTP Nexus
    # - docker login -u nexususer -p nexuspassword <yourdomain.com>:8443  # HTTPS Nexus
  script:
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $NEXUS_IMAGE_NAME
    - docker push $NEXUS_IMAGE_NAME
  tags:
    - docker
    - app01

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --no-cache openssh-client
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-keygen -q -N "" -f id_rsa
    - chmod 400 id_rsa
    - ssh-keyscan -H $APP_HOST >> ~/.ssh/known_hosts
    - ssh -i id_rsa ubuntu@$APP_HOST "docker stop app01 || true && docker rm app01 || true"
  script:
    - ssh -i id_rsa ubuntu@$APP_HOST "docker pull $NEXUS_IMAGE_NAME"
    - ssh -i id_rsa ubuntu@$APP_HOST "docker run -d -p 8000:8000 --name app01 $NEXUS_IMAGE_NAME"
  environment:
    name: production
    url: http://$APP_HOST:8000
  variables:
    APP_HOST: "89.169.187.68"
  tags:
    - docker
    - app01

stop_environment:
  stage: cleanup
  image: docker:latest
  when: manual
  environment:
    name: production
    action: stop
  before_script:
    - apk add --no-cache openssh-client
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-keygen -q -N "" -f id_rsa
    - chmod 400 id_rsa
    - ssh-keyscan -H $APP_HOST >> ~/.ssh/known_hosts
  script:
    - ssh -i id_rsa ubuntu@$APP_HOST "docker stop app01 || true && docker rm app01 || true"
    - docker login -u admin -p Tanktank12 89.169.189.228:5000 # HTTP Nexus
    # - docker login -u nexususer -p nexuspassword <yourdomain.com>:8443 # HTTPS Nexus
    - ssh -i id_rsa ubuntu@$APP_HOST "docker rmi $NEXUS_IMAGE_NAME || true"
    - ssh -i id_rsa ubuntu@$APP_HOST "curl -X DELETE -u nexususer:nexuspassword http://89.169.189.228:8081/service/rest/v1/repository/docker/<repo_name>/<image_name>:<tag>" # Nexus API
  variables:
    APP_HOST: "89.169.187.68"
  tags:
    - docker
    - app01
