---
# roles/kafka_ui/tasks/main.yml

- name: Обновляем список пакетов
  ansible.builtin.apt:
    update_cache: yes

- name: Устанавливаем Docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Pull Kafka UI Docker image
  docker_image:
    name: provectuslabs/kafka-ui
    tag: latest
    source: pull

- name: Run Kafka UI container
  docker_container:
    name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    state: started
    restart_policy: always
    ports:
      - "{{ kafka_ui_external_port }}:{{ kafka_ui_internal_port }}"
    env:
      KAFKA_CLUSTERS_0_NAME: "{{ kafka_cluster_name }}"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "{{ kafka_bootstrap_servers }}"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "{{ kafka_zookeeper }}"

     