---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Pull Kafka UI Docker image
  docker_image:
    name: provectuslabs/kafka-ui
    tag: latest
    source: pull

- name: Run Kafka UI container
  docker_container:
    name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
    env:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "{{ hostvars['kafka01'].ansible_host }}:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "{{ hostvars['kafka01'].ansible_host }}:2181"