---
# roles/clickhouse/tasks/main.yml

- name: Обновляем кэш пакетов apt
  ansible.builtin.apt:
    update_cache: yes

- name: Устанавливаем необходимые пакеты
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - dirmngr
      - gnupg
      - curl
    state: present

- name: Скачиваем и добавляем ключ ClickHouse GPG
  ansible.builtin.shell: |
    curl -fsSL 'https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key' | gpg --dearmor -o /usr/share/keyrings/clickhouse-keyring.gpg
  args:
    creates: /usr/share/keyrings/clickhouse-keyring.gpg

- name: Добавляем репозиторий ClickHouse в список источников
  ansible.builtin.shell: |
    echo "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.gpg] https://packages.clickhouse.com/deb stable main" | tee /etc/apt/sources.list.d/clickhouse.list
  args:
    creates: /etc/apt/sources.list.d/clickhouse.list

- name: Обновляем кэш пакетов после добавления пакетов
  ansible.builtin.apt:
    update_cache: yes

- name: Устанавливаем ClickHouse
  ansible.builtin.apt:
    name:
      - "clickhouse-server={{ clickhouse_version }}"
      - "clickhouse-client={{ clickhouse_version }}"
      - "clickhouse-common-static={{ clickhouse_version }}"
    state: present

- name: Запускаем и включаем ClickHouse
  ansible.builtin.systemd:
    name: clickhouse-server
    state: started
    enabled: yes

- name: Применяем SQL-шаблон для настройки ClickHouse
  ansible.builtin.template:
    src: "database.xml.j2"
    dest: "/tmp/database.xml"

- name: Выполняем настройку ClickHouse
  ansible.builtin.shell: |
    cat /tmp/database.xml | clickhouse-client --host {{ clickhouse_host }} --port {{ clickhouse_port }} --user {{ clickhouse_user }} --password '{{ clickhouse_password }}' --multiquery
  args:
    executable: /bin/bash
  when: clickhouse_user is defined and clickhouse_password is defined
